export const PLAY_BUTTON = 'PLAY_BUTTON';

export const STOP_BUTTON = 'STOP_BUTTON';

export const INCREMENT_TIMER = 'INCREMENT_TIMER';

export const RESET_TIMER = 'RESET_TIMER';

export const INCREMENT_PROGRESS_BAR = 'INCREMENT_PROGRESS_BAR';

export const RESET_PROGRESS_BAR = 'RESET_PROGRESS_BAR';